apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-faas
  labels:
    app: nodejs-faas
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nodejs-faas
  template:
    metadata:
      labels:
        app: nodejs-faas
    spec:
      containers:
      - name: nodejs-faas
        image: shreyasnayak21/nodejs-faas:beta
        ports:
        - containerPort: 9256
        env:
        - name: JWT_KEY
          value: "1X2A0p84VmmLF3NYz3uHPx1hLuhT2U24"
        volumeMounts:
        - name: functions-volume
          mountPath: /opt/app/storage/functions
      volumes:
      - name: functions-volume
        persistentVolumeClaim:
          claimName: functions-pvc