name: Node.js CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-deploy:
    runs-on: node:20-bookworm-slim

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'v18.17.0'

      - name: Install Dependencies
        run: npm install

      - name: Run Build (optional)
        run: npm run build

      - name: Run Tests (optional)
        run: npm test

    Optional: Docker image build & push
      - name: Build Docker Image
        run: docker build -t shreyasnayak21/nodejs-faas:beta .

      # - name: Push to DockerHub or GHCR
      #   run: echo "push step here"

      # Example Deploy: rsync to server (update credentials & IP)
      # - name: Deploy to Server
      #   run: rsync -avz ./ user@your-server-ip:/opt/nodejs-faas/
      #   env:
      #     SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
