name: Docker Image CI

on:
  push:
    tags:
      - '*'  # Triggers on any tag push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build the Docker image
      run: docker build . -f Dockerfile -t shreyasnayak21/nodejs-faas:${{ github.ref_name }}

    - name: Push Docker image
      run: docker push shreyasnayak21/nodejs-faas:${{ github.ref_name }}
